dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest-travis-fold


before_script:
  - cd tests

#script:
#  - pytest

script:
  - python test_Calc.py