#dist: xenial
os: osx
osx_image: xcode7.3 # macOS 10.11
name: '10.11'
arch: amd64
cache: *osx_cache
language: python
python:
  - "3.7"

install:
  - pip install pytest==4.6.3
  - pip install packaging
  - pip install setuptools
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pytest-travis-fold


before_script:
  - cd tests

script:
  - pytest

#script:
#  - python test_Calc.py
